name: release
on:
  release:
    types: [published, edited]
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: set version
      run: sed -i'' -e $'s/0.0.0/${{ github.ref_name }}/g' src/Kernel.csproj

    - name: dotnet pack
      run: dotnet pack "src/Kernel.csproj" -c Release -o ./dist

    - name: nuget publish
      run: dotnet nuget push "./dist/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s ${{ secrets.NUGET_SOURCE }}