name: deploy
on:
  release:
    types: [published, edited]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: get release version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: install powershell
      run: dotnet tool install --global PowerShell

    - name: set release version
      run: pwsh ./release.ps1 ${{ steps.get_version.outputs.VERSION }}

    - name: github package
      run: dotnet nuget add source https://nuget.pkg.github.com/mobnet/index.json -n "github" -u JezielMoura -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: dotnet pack
      run: dotnet pack "Mobnet.SharedKernel.csproj" -c Release -o ./dist

    - name: nuget publish
      run: dotnet nuget push "./dist/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "github" --skip-duplicate