name: dotnet
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        
    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore
      
    - name: test
      run: dotnet test --configuration Release --no-build  --collect:"XPlat Code Coverage" 

    - name: upload report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage-report
        retention-days: 7