name: dotnet
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

    - name: test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura 

    - name: budge
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: test/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: install report generator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.9

    - name: run report generator
      run: reportgenerator -reports:"test/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html

    - name: upload report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coveragereport
        retention-days: 7